#UDP client (rename this something sane!)
GXX=g++
CFLAGS=-g -std=c++11


all:	client2 server2

client2: client2.cc
	$(GXX) $(CFLAGS) client2.cc -o client2

server2: server2.cc
	$(GXX) $(CFLAGS) server2.cc -o server2
