#Animals
GXX=g++
CFLAGS= -std=c++11
SOURCES = main.cpp Animal.h Animal.cpp Dog.h Dog.cpp Cat.h Cat.cpp

all:	main 

main:  
	$(GXX) $(CFLAGS) $(SOURCES) -o main.out

.PHONY: clean

clean:
	 rm -f main
	 